# 今回使うDockerの参照元のイメージ
FROM ruby:3.3.6

# なんやかんやおまじない
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

# node.jsやらyarnやらなんやらをシステム全体にインストール
RUN apt-get update -qq \
&& apt-get install -y ca-certificates curl gnupg \
&& mkdir -p /etc/apt/keyrings \
&& curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
&& NODE_MAJOR=20 \
&& echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
&& wget --quiet -O - /tmp/pubkey.gpg https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
&& echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential git libpq-dev fonts-noto-cjk pkg-config python-is-python3 \
    fonts-noto-color-emoji libglib2.0-dev libcairo2-dev libpango1.0-dev \
    libatk1.0-dev libgdk-pixbuf2.0-dev libgtk-3-dev \
    libffi-dev libgirepository-1.0-1 libgirepository1.0-dev && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives && \
    fc-cache -f -v

# Chrome dependencies
RUN apt-get update && apt-get install -y \
    curl gnupg unzip xvfb \
    && rm -rf /var/lib/apt/lists/*

# Install Google Chrome
RUN curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-linux.gpg \
    && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux.gpg] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list \
    && apt-get update && apt-get install -y google-chrome-stable

# ディレクトリを作成してそれを作業ディレクトリ（Dockerが操作するディレクトリ）に設定
RUN mkdir /myapp
WORKDIR /myapp
RUN gem install bundler

# Dockerfileが存在するディレクトリ内（コンテナの外。今回の場合はRailsのアプリがあるディレクトリ）
# にあるすべてのファイルとサブディレクトリをコンテナ内の/myappにコピー
COPY . /myapp